openapi: 3.0.0
info:
  title: PsiBorg_Assignment
  version: 1.0.0
servers:
  - url: http://localhost:8080
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
tags:
  - name: Users
  - name: Task
  - name: Auth
paths:
  /psiborg/user/getUserProfile:
    get:
      tags:
        - Users
      summary: Get User Profile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /psiborg/task/create:
    post:
      tags:
        - Task
      summary: Create Task
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                title: Complete Project Documentation
                assignedTo: vatsal
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /psiborg/task/delete/{id}:
    delete:
      tags:
        - Task
      summary: Delete Task
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /psiborg/task/update/{id}:
    put:
      tags:
        - Task
      summary: Update Task
      requestBody:
        content: {}
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /psiborg/task/getAllTask:
    get:
      tags:
        - Task
      summary: Get All Tasks
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
          example: completed
        - name: priority
          in: query
          schema:
            type: string
          example: medium
        - name: sortBy
          in: query
          schema:
            type: string
          example: dueDate
        - name: order
          in: query
          schema:
            type: string
          example: desc
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /psiborg/auth/register:
    post:
      tags:
        - Auth
      summary: User Registration
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: vatsa23
                email: vatsalthapliyal00@gmail.com
                password: Vatsal@23
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /psiborg/auth/login:
    post:
      tags:
        - Auth
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: manager2@gmail.com
                password: Manager00@2
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
  /psiborg/auth/logout:
    post:
      tags:
        - Auth
      summary: Logout
      requestBody:
        content: {}
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}